### ISSUE TITLE
Not taking multiline matrix

### ISSUE THREAD

**Issue by karnprem90** [mehdisadeghi/react-mathjax-preview#1]

**Comment by mehdisadeghi** [comment]
@karnprem90 can you give an example of such a matrix please?

**Comment by karnprem90** [comment]
$ If \[\left| \begin{matrix}
a &amp; b-c &amp; c+b \\
a+b &amp; b &amp; c-a \\
a-b &amp; a+b &amp; c \\
\end{matrix} \right|=0,\] =0 $

Try this one

**Comment by mehdisadeghi** [comment]
@karnprem90 Your sample does not render on [mathjax](https://www.mathjax.org). There is a demo on that page, try to run your example there. If it does not work there it might be a MathJax bug. If it works there but not with `react-mathjax-preview`, then it is a bug of this program.

**Comment by mehdisadeghi** [comment]
I will close this issue as invalid, please report the bug to the upstream (MathJax). Feel free to reopen if you think we can improve anything here.

**Comment by karnprem90** [comment]
It is running in mathjax please find attched image

![screen shot 2017-10-26 at 5 02 46 pm](https://user-images.githubusercontent.com/9381098/32050796-c3a1f29e-ba6f-11e7-91c7-1a05aa759635.png)
Please have a look.

**Comment by mehdisadeghi** [comment]
@karnprem90 This example works fine in `react-mathjax-preview`:

![image](https://user-images.githubusercontent.com/3101557/32053631-307f740e-ba5c-11e7-8d59-a93a67c00919.png)
