### ISSUE TITLE
bug: react-mathjax-preview@0.1.12 is an empty package 

### ISSUE THREAD

**Issue by douglasduteil** [mehdisadeghi/react-mathjax-preview#14]
I'm afraid nothing got pack in the latest `react-mathjax-preview@0.1.12` version :fearful: 

\see https://unpkg.com/browse/react-mathjax-preview@0.1.12/

**Comment by mehdisadeghi** [comment]
@douglasduteil thanks for letting me know. I'm looking at this right now! :sweat_smile:

**Comment by mehdisadeghi** [comment]
I published a [new version 0.1.13](https://unpkg.com/browse/react-mathjax-preview@0.1.13/) with the missing files. Let me know if anything else is missing!

**Comment by douglasduteil** [comment]
LGTM :+1: 
Thanks @mehdisadeghi
