### ISSUE TITLE
Use latest MathJax 2.7.x

### ISSUE THREAD

**Issue by Cmdr3nder** [mehdisadeghi/react-mathjax-preview#17]
So I noticed that MathJax has had several releases since `2.7.0`.

I suggest updating to `2.7.6` since `3.0` might have large changes to avoid with it only being 7 days old at the time of writing.

Is there a reason not to update to `2.7.6` I haven't discovered?

**Comment by mehdisadeghi** [comment]
> Is there a reason not to update to 2.7.6 I haven't discovered?

Not at all. Thanks for the PR.

**Comment by mehdisadeghi** [comment]
@Cmdr3nder just published a  [new release](https://unpkg.com/browse/react-mathjax-preview@0.1.15/).
