### ISSUE TITLE
Type of propTypes.style should be object

### ISSUE THREAD

**Issue by bhead-mi** [mehdisadeghi/react-mathjax-preview#28]
Passing an object into the default component causes a warning in Chrome DevTools. Passing a string into the `react-mathjax-preview` div causes a Javascript error. Changing the type of `propTypes.style` to `PropTypes.object` will eliminate the warning.

In demo/src/index.js, line 118, style is passed in as an object: 
    ```<Example math={this.state.math} style={{marginTop: '20px'}}/>```

The warning from Chrome DevTools: Warning: Failed prop type: Invalid prop `style` of type `object` supplied to `_class`, expected `string`.

**Comment by mehdisadeghi** [comment]
@bhead-mi thanks for reporting. Just fixed that.
