### ISSUE TITLE
Taking multiline matrix in MathJax but there is some issue  in this module

### ISSUE THREAD

**Issue by karnprem90** [mehdisadeghi/react-mathjax-preview#3]
Please find the attached image
![screen shot 2017-10-26 at 5 02 46 pm](https://user-images.githubusercontent.com/9381098/32051794-a643ff90-ba73-11e7-878e-a388176b3f49.png)

$If [\left| \begin{matrix}
a & b-c & c+b \
a+b & b & c-a \
a-b & a+b & c \
\end{matrix} \right|=0,] =0 $

**Comment by mehdisadeghi** [comment]
@karnprem90 I can't tell the difference, this is my demo:

![image](https://user-images.githubusercontent.com/3101557/32053720-764eba1c-ba5c-11e7-8879-82997023e6b4.png)

What are the _issues_ that you are referring to?

**Comment by karnprem90** [comment]
I am using react quill rich editor. Where I do copy paste of multiline equation which doesn't parse into latex equation? I am just passing equation in <MathJax math={this.state.equation} />.It is not working for multiline only. 
Another example is 
Equation =

> $\Delta =\left| \begin{matrix}
>   a & b & c \\
>   b & c & a \\
>   c & a & b \\
> \end{matrix} \right|$
> 

It is not working, but if I do something like this

> $\Delta =\left| \begin{matrix}a & b & c \\ b & c & a \\c & a & b \\\end{matrix} \right|$

It is working perfectly fine but for multiline it's not working.

**Comment by mehdisadeghi** [comment]
@karnprem90 If I understand correctly, you have an editor that you paste your math there and then you (programmatically) pass it to `react-mathjax-preview` and when your math is multi-line it does not work.

I think your editor is probably modifying line-feeds and replacing them or doing something similar that causes the problem. If you paste your above multi-line math inside the demo page of the component, you'll see that it displays correctly.

**Comment by mehdisadeghi** [comment]
As far as I can tell this is an editor problem (as described in the latest comment), therefore I close this issue. Feel free to reopen (or submit a PR) if you think the error is in this program.
