### ISSUE TITLE
Iframe is not displayed

### ISSUE THREAD

**Issue by henok-tesfaye** [mehdisadeghi/react-mathjax-preview#30]
```
<h3 dir="ltr">Watch This Video About Raising Anorexia Awareness:</h3>

<p><iframe allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen="" frameborder="0" height="315" src="https://www.youtube.com/embed/aTIjRxT_Y9g" width="560"></iframe></p>
```

This snippet code doesn't show the video in the iframe, tested in https://focused-tesla-b6fe0a.netlify.com/.
However it works as expected in online html editors, https://html-online.com/editor/.

**Comment by mehdisadeghi** [comment]
You're supposed to enter TeX, MathML or asciimath not html.
