### ISSUE TITLE
No files in package 1.0.0

### ISSUE THREAD

**Issue by UnbearableBear** [mehdisadeghi/react-mathjax-preview#32]
Hi,

First of all, thanks for this package !

I tried to use the 1.0.0 version but all I got in the package was this:

<img width="162" alt="Screenshot 2020-02-26 at 16 59 50" src="https://user-images.githubusercontent.com/705453/75364340-dee68780-58bb-11ea-966f-3ceec96d7dba.png">

Did you build the `lib` and `es`folder before publishing ? Not sure what's wrong but 1.0.0 cannot be imported in my project for sure :(

**Comment by mehdisadeghi** [comment]
@UnbearableBear thanks for reporting. I had a problem during upload and apparently I have uploaded the wrong package. I'll fix it right away.

**Comment by mehdisadeghi** [comment]
I just released a new version `1.0.1` with the missing content. Let me know if it solves the issue please.

I am also migrating the package from nwb to neutrinojs to avoid such problems in future. See #34

**Comment by UnbearableBear** [comment]
The issue seems solved thanks for the quick fix :)
If you are looking for something lighter for bundling purposes, we use https://github.com/rollup/rollup on our project and we love it !

**Comment by mehdisadeghi** [comment]
@UnbearableBear it looks really good. Thanks for letting me know!

I close the issue. Feel free to reopen if the issue persists.
