### ISSUE TITLE
Dynamic script URL

### ISSUE THREAD

**Issue by nkrmr** [mehdisadeghi/react-mathjax-preview#35]
Hello,

Is it possible to set dynamically the script URL due to SCP issue?
Maybe we can define a props ***"script"*** into the component to set a default path to MatJax script.

Best regards,

**Comment by mehdisadeghi** [comment]
Hello @nkrmr,

> Is it possible to set dynamically the script URL due to SCP issue?

Upon the first page load it should be no problem to set the script URL. There are some issues though. Please read below. btw, what do you mean by "SCP issue"?

The base URL is currently one version behind the latest MathJax v2 release ([v2.7.7](https://github.com/mathjax/MathJax/releases/tag/2.7.7) is the latest). Any version higher than v2.7.7 is [MathJax v3](https://github.com/mathjax/MathJax-src/releases) and is not backward compatible. So some work should be done on that front.

The next issue is the configuration. Setting the configurations (the `config` param in the URL) dynamically in React code did not work at all and the current script URL worked best. Any other config broke some feature. Please see [MathJax Combined Configurations](http://docs.mathjax.org/en/v2.6-latest/config-files.html#common-configurations).

The last but not least, I have reorganized the repo in the [neutrinojs](https://github.com/mehdisadeghi/react-mathjax-preview/tree/neutrinojs) branch. Consider that in case of any PRs.

Feel free to submit a PR if you have a better solution for any of the problems above.

**Comment by nkrmr** [comment]
Hi, @mehdisadeghi 

Thanks for the answer.

I'm talking about this SCP issue : 
![Screenshot 2020-03-04 at 15 33 41](https://user-images.githubusercontent.com/686395/75889755-adc30580-5e2d-11ea-8fd1-9bd5a3c6f806.png)

On IE this makes the formula disappear after a couple of seconds.
Maybe you already had this issue, if not I'm going to try making a PR to fix it.

Best regards,

**Comment by mehdisadeghi** [comment]
Hi @nkrmr,

Thanks for explaining the issue. A PR is very much appreciated.

Cheers

**Comment by nkrmr** [comment]
@mehdisadeghi Added PR #43

**Comment by nkrmr** [comment]
@mehdisadeghi Hi, thanks for the merge. 
Is it possible to know when the next release is?

**Comment by mehdisadeghi** [comment]
Hi @nkrmr . Sure, I'll release this evening.

**Comment by mehdisadeghi** [comment]
@nkrmr just released <strike> [`1.2.0`](https://unpkg.com/browse/react-mathjax-preview@1.2.0/). </strike>

Edit: had to repbulish [`1.2.1`](https://unpkg.com/browse/react-mathjax-preview@1.2.1/dist/index.js) immediately because there was a problem and I don't know how to replace or remove a package from npm once it is released.

**Comment by nkrmr** [comment]
@mehdisadeghi  Thanks a lot for the release

**Comment by mehdisadeghi** [comment]
You're welcome! :)
