### ISSUE TITLE
Render problem in the React app

### ISSUE THREAD

**Issue by GongYanfu** [mehdisadeghi/react-mathjax-preview#44]
in the react app, when I change the router to a new page which includes Latex, It doesn't work. I have to refresh the page manually and then it works.
firstly:
![image](https://user-images.githubusercontent.com/46698455/78213783-31801880-74e6-11ea-993a-72407c1e3965.png)
![image](https://user-images.githubusercontent.com/46698455/78213826-53799b00-74e6-11ea-8aac-eeb2a7750649.png)

**Comment by mehdisadeghi** [comment]
Could you provide a minimal example that demonstrates the bug please?

**Comment by hirdeshtomar** [comment]
@mehdisadeghi  I am also facing the same issue.  
A simple React Component that receives "math text to display" as props from parent component, needs page refresh to show MathJax text preview.

**Comment by mehdisadeghi** [comment]
@hirdeshtomar what is the difference between the your react app and the demo on this repository? Does it work with older versions than 1?

I can only work on the issue if I can reproduce it.

**Comment by Zaynex** [comment]
Because when you re-render , loadingState is still loading. ScriptTag onload  event only trigger once. 
Quick fix:

```
 useEffect(() => {
    if (loadingState !== 'loaded' && !window.MathJax) {
      return
    }
    previewRef.current.innerHTML = sanitizedMath
    window.MathJax.Hub.Queue([
      'Typeset',
      window.MathJax.Hub,
      previewRef.current
    ])
  }, [sanitizedMath, loadingState, previewRef])
```

@GongYanfu  @hirdeshtomar

**Comment by mehdisadeghi** [comment]
@Zaynex thanks! Can you make your quick fix it into a quick PR?

**Comment by hirdeshtomar** [comment]
@Zaynex - Is this quick fix to be done inside react-mathjax-preview library?
