### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by nkrmr** [mehdisadeghi/react-mathjax-preview#45]
@mehdisadeghi I have a build issue with the next release : 

<img width="1680" alt="Screenshot 2020-04-03 at 14 34 11" src="https://user-images.githubusercontent.com/686395/78361216-547afd00-75b8-11ea-9dee-6ad76e29092d.png">

**Comment by mehdisadeghi** [comment]
@nkrmr I think I know why you get this error. Current build output is set to *esmodule*. I am changing that, it will remove the import statements.

**Comment by nkrmr** [comment]
@mehdisadeghi Thanks, it is possible to have a release with this fix quickly?

**Comment by mehdisadeghi** [comment]
@nkrmr sure! I will release in a few minutes.

**Comment by mehdisadeghi** [comment]
@nkrmr please try [`1.2.2`](https://unpkg.com/browse/react-mathjax-preview@1.2.2/dist/index.js) and let me know whether it solves the problem. Feel free to reopen if something fails.

**Comment by nkrmr** [comment]
@mehdisadeghi It works better, thanks a lot 💪
