### ISSUE TITLE
allow to configure root tags rendered by MathJaxPreview

### ISSUE THREAD

**Issue by bertrand-riviere** [mehdisadeghi/react-mathjax-preview#57]
hello,
first, thanks for this nice component, it is very useful!

i ran into an issue because i need to render MathJax components inside `<p>` elements (and i cannot change that); this causes an annoying React warning: "Warning: validateDOMNesting(...): `<div>` cannot appear as a descendant of `<p>`."
(+ this warning actually makes sense since it is not semantically correct to put `<div>` inside `<p>`)

i wondered if you would accept a PR that allows to configure the tag, ex:
`React.createElement(tag, ...)` where "tag" is a new prop of MathJaxPreview instead of the "hardcoded" `<div>` s that are actually rendered?
by having a defaultProps for "tag" of 'div', the behaviour would remain the same than today and i (+ others) could use this new props to avoid similar problems.

**Comment by mehdisadeghi** [comment]
Hi @bertrand-riviere , You are very welcome to send me a PR if you have a fix for that.
